### PR TITLE
FLASH->hasKey, Flash example fixes

### PR DESCRIPTION
**Pull request by rolandtoth**
fixed $flash->addKey to $flash->setKey
added $flash->hasKey
added $flash->hasKey example

### CODE REVIEW

**Comment by ikkez** [comment]
oh yes, that looks good. thanks

**Comment by rolandtoth** [comment]
Thanks!

Btw, why do you use `<F3:check` instead of only `<check>`? Compability?

**Comment by ikkez** [comment]
No both ways are compatible. It's just that my PHPStorm IDE highlights such tags that have a : namespace ;) so i can see F3 directives faster when i scroll through my templates. See:
screenshot 2015-02-05 16 25 49

**Comment by rolandtoth** [comment]
I also use PhpStorm and you are right, it is easier to see. Thanks for the
tip!

**Pull request merged**
