### PR TITLE
Typos

### PR DESCRIPTION
**Pull request by emanwebdev**
Discovering your Sugar! Amazing!!! why not put these plugins on the F3Com website?

### CODE REVIEW

**Comment by ikkez** [comment]
> Discovering your Sugar! Amazing!!! why not put these plugins on the F3Com website?

There is a hint at http://fatfreeframework.com/development#user-plugins ;)
But i see it's not that up-to-date :)

**Comment by emanwebdev** [comment]
> There is a hint at http://fatfreeframework.com/development#user-plugins ;)

oh, i see! but i don't go that often to that page :/ yes, i see your name everywhere on the page now ;))  Gosh! you'r a kickass programmer actually! and i piss you with fucking missing coma, and pointless sub-microscopic details! geee.... sorry for your precious time!!! that's the end anyway, and you sanely survived ;)

i looked at your creations, yeah, too quickly for sure, Wow! the SchemaBuilder's hard work,no? verbose verbose :)  i don't see too much of an use to me as SQL allows to do it straightforward but for the beauty of the composition, and for pax who don't know SQL enough

i like the Cortex!!! like the idea to have an abstraction layer so a website can one day move from Jig to SQLite then MySQL seamlessly 3>   the performance Dream :))))
As a test, i will see if i can try to load existing MySQL table to see if i can translate them to SQLite and Jig

Well, many things to try now :) Thanks !!!

Oh, one more thing:
Your Route plug-in is a legacy one? i mean, now with F3 v.3.2+, names routes are native for not so long. I guess this plugin is here coz you had the idea long time ago ;)
And i remember i read something about anchor tags replacement. To check. 
I'll be back

**Comment by ikkez** [comment]
hehe, thanks for the flowers :) 
yeah it wasn't that easy to keep on track with you :sweat_smile: you are almost faster with writing, than i can review it all ^^

The sql schema builder was hard work, indeed. So many sleepness nights :sleeping: and tons of manuals i digged through. It'll be useful if you plan any bigger software, maybe with a plugin / modules system. Using this db layer ensures that your app and any 3rd party made plugin used in there can still run on different database engines. i.e. for CMS environments. Not every plugin author is willed to add multiple schema queries for installing his plugin. And mostly they can't test them on every engine. That's the purpuse of the Schema Builder ;)

Cortex was the next big thing :) well, the idea of it goes back to before i wrote the schema tool. But somehow it was missing and in needed it for cortex. So this had to wait for a long time, but now it's all there and hopefully stable =)
Though i haven't tested a fully migration (incl. relations) between engines with cortex, yet. But at least it runs already fine on each of them. Have a look at my little blog script that utilizes Cortex: [fabulog](https://github.com/ikkez/fabulog) :)
While coding all that, i tend to neglect keeping the docs updated, so thanks for some pushes in the right direction and helping with all those annoying docs... i guess nobody really loves to write docs as much as you do :grinning: 

The Router plugin.. yes it's somehow obsolete now since named routes come into play in v3.2. But the anchor view helper could still be useful. Well i don't know what to do with it now. But at least it's still working and i think i'll focus on other things first before touching this again.

**Comment by emanwebdev** [comment]
> fabulog

i like it very much!!! you good!!  excellent design!! thanks to BS3, but anyway, you did it!!  

just to have an idea, how much work for you to setup this baby?

P.S.
sorry<, i made a mistake, maybe this can be of any help to you?
probably nothing big, it's when trying to save a new post,
[deleted to not expose the server]

**Comment by ikkez** [comment]
> just to have an idea, how much work for you to setup this baby?
> well hard to say, because i wrote this to test the abilities of cortex and fixed some bugs in it and F3 mappers along the road, which also takes some times... and i played a bit with [RMR](http://www.peej.co.uk/articles/rmr-architecture.html) ... but all together maybe 1 or 2 month..(always just some hours in the evening).. but i bet it's possible in a 1 or 2 weeks streak now 

regarding your error: i cannot reproducte this atm... i just downloaded a fresh copy, unzip, set some file permissions and done... saving new posts works here.
What PHP version do you use?

**Comment by emanwebdev** [comment]
> What PHP version do you use?

i don't know, it happened on YOUR server actually

in the admin, go to http://www.ikkez.de/fabulog/admin/post/create 
and do nothing but scroll down to click the 'Save' button. That's just a missing `if` ;)  always the same story

**Comment by emanwebdev** [comment]
> RMR

yes, remember now you speak about it in the doc.... _time warp_  so I took time to read the representation of the resource you pointed me to ;)  actually, i found it better, albeit v. close, than MVC . and the concept matches well with a F3 route associated to a class/method

_timewarp_

i see "build with RMR architecture"   

I'd like to download your fabulog to learn. can't see what license do you offer?

**Comment by ikkez** [comment]
on my server? hm well seems to work here,.. and someone already had fun with it ^^
well this RMR thing was a little experiment for me to see if it would be usable or not. Actually i think it introduces more drawbacks than in solves... i.e. a complete map() to the model isn't usable, because the HTTP VERB method like get() is already taken by the magic function. It was a nice excursion but i guess next time i'll stick to map to controllers, rather than putting everything in the models :D

fabulog is MIT ( GPLv3 compatible )

**Pull request merged**
