### PR TITLE
SchemaBuilder: data types naming convention

### PR DESCRIPTION
**Pull request by xfra35**
Hi ikkez, I didn't have a chance to try your SchemaBuilder plugin before. That's good work!

I bring here a suggestion for renaming the numeric types. I find the naming convention quite confusing since INT8 is 8 bits, but INT16 is 32 bits. I suggest naming them according to the target storage length: INTxx = xx bits.
Therefore we would have INT8, INT16, INT32 and INT64.
Moreover I changed the pgsql type for INT8 to `smallint` since it's closer to `tinyint` than `integer`.

### CODE REVIEW

**Comment by xfra35** [comment]
Also for the text types, we could name them VARCHAR128, VARCHAR256, VARCHAR512, TEXT, LONGTEXT (cf. last commit).
I think the meaning would then be clearer.

**Comment by ikkez** [comment]
hi Florent, thanks for using and improving the schema plugin.
Yeah it's a good idea to improve that and making it more clearer. But i'm not sure about every change you've made. I'll consider it deeper and check all docs again to be sure. And maybe we can stick to bytes than bits to make the names shorter and follow the descriptions in most db engine docs... so it would become INT2, INT4, INT8... and so on.
I'll take a look on this later today or tomorrow when i have some more time. 
But thanks again ;) i really appreciate it.

**Comment by marcuseby** [comment]
I don't know if this helps or not, but I did the same renaming and expanding, but I tried not to make anything too long, so I like the idea of VARCHAR128, 256, 512, etc, but for the INT's I prefer going to bit/byte size as I find it easier to read when developing a DB. 
For VARCHARS, I went with VARCHARSM, VARCHARMD, and VARCHARLG, and MEDTXT, TEXT, but I like xfra's suggestions better for text types.

Marcus

**Comment by xfra35** [comment]
I sticked to bits because I thought that was your initial logic, but I also prefer bytes (INT1, INT2, INT4, INT8) for consistency (varchar length is defined in bytes).

**Comment by ikkez** [comment]
fixed in new dev-schema branch

**Pull request closed without merging**
